---
all: #all servers
  hosts: #ungroupd
    host1: # hosts1 in ungroupd 
      ansible_host: 
  children:
    group1: #group
      hosts:
        host1:
          ansible_host: 10.108.0.4
    group2: #group name
      hosts:
        host2:
          ansible_host: 10.108.0.3
        
             